In [1]:
import pandas as pd
import numpy as np


In [2]:
columns = ["stationcode", "datelabel", "param", "value", "mflag", "qflag", "sflag", "time"]
df = pd.read_csv("./data/NCEI/ghcn/daily/1949.csv.gz", names=columns, compression="gzip")


In [3]:
df.head()

stationcode  datelabel param  value mflag qflag sflag  time
0  ACW00011604   19490101  TMAX    289   NaN   NaN     X   NaN
1  ACW00011604   19490101  TMIN    217   NaN   NaN     X   NaN
2  ACW00011604   19490101  PRCP      0   NaN   NaN     X   NaN
3  ACW00011604   19490101  SNOW      0   NaN   NaN     X   NaN
4  ACW00011604   19490101  SNWD      0   NaN   NaN     X   NaN

In [12]:
df["param"].unique()

array(['TMAX', 'TMIN', 'PRCP', 'SNOW', 'SNWD', 'TAVG', 'WT01', 'PGTM',
       'WDFG', 'WSFG', 'WT16', 'WT03', 'WT09', 'WT18', 'MDPR', 'MDSF',
       'WT04', 'WT06', 'WT08', 'TOBS', 'WT07', 'EVAP', 'WDMV', 'WT11',
       'WT14', 'DAPR', 'WT05', 'GAHT', 'FRGB', 'FRGT', 'FRTH', 'DWPR',
       'DATX', 'MDTX', 'DASF', 'DAWM', 'MDWM', 'DATN', 'MDTN', 'THIC',
       'WT10', 'DAEV', 'MDEV', 'MXPN'], dtype=object)

In [13]:
df["time"].unique()

array([  nan,  800.,  700., 1700.,  600., 1800., 1600., 1300.,  500.,
       1900., 1830., 1000.,  900., 2400., 2100., 1500., 2300., 2000.,
       1400., 1200.,  815., 1100.,  630.,  730., 1630.,  645., 2200.,
       1230.,  830., 1730.,  100.,  930., 1530., 1430.])

In [14]:
dffiltered = df[df["param"].isin(["TMAX", "TMIN", "PRCP", "SNOW", "SNWD"])]

In [15]:
dffiltered["param"].unique()

array(['TMAX', 'TMIN', 'PRCP', 'SNOW', 'SNWD'], dtype=object)

In [16]:
dffiltered["time"].unique()

array([  nan,  800.,  700., 1700.,  600., 1800., 1600., 1300.,  500.,
       1900., 1830., 1000.,  900., 2400., 2100., 1500., 2300., 2000.,
       1400., 1200.,  815., 1100.,  630.,  730., 1630.,  645., 2200.,
       1230.,  830., 1730.,  100.,  930., 1530., 1430.])

In [17]:
df.size

190296952

In [18]:
dffiltered.size

170047232

In [21]:
dffiltered["mflag"].unique()

array([nan, 'T', 'B', 'P', 'D'], dtype=object)

In [29]:
missing = dffiltered[dffiltered["mflag"].isin(["P"])]

In [30]:
missing

stationcode  datelabel param  value mflag qflag sflag    time
17798     RQC00667292   19490101  PRCP      0     P   NaN     6     NaN
17812     RQW00011603   19490101  PRCP      0     P   NaN     6   800.0
23122     USC00018925   19490101  PRCP      0     P   NaN     6     NaN
25858     USC00044705   19490101  PRCP      0     P   NaN     6  2400.0
28504     USC00084262   19490101  PRCP      0     P   NaN     6     NaN
...               ...        ...   ...    ...   ...   ...   ...     ...
23781849  USC00515404   19491231  PRCP      0     P     L     6   600.0
23782107  USC00518217   19491231  PRCP      0     P     L     6   800.0
23782127  USC00518385   19491231  PRCP      0     P   NaN     6     NaN
23782249  USC00519014   19491231  PRCP      0     P     L     6     NaN
23786450  USW00093104   19491231  PRCP      0     P   NaN     6   700.0

[26897 rows x 8 columns]